export const seedData = {
  settings: {
    theme_color: 'teal' as const,
    color_mode: 'light' as const,
  },
  profile: {
    name: 'Harish Khuva',
    headline: 'Multi-Platform Web Developer',
    subheadline:
      '3+ years building high-performing websites and stores — 40+ WordPress sites, 10+ Shopify stores, and custom GHL API integrations.',
    bio: "I'm Harish Khuva, a web developer with 3+ years of experience building and launching digital platforms across WordPress, Shopify, Webflow, GoHighLevel (GHL), and Wix Studio. I've delivered 40+ WordPress websites, 10+ Shopify stores, and hands-on GHL API integrations — plus experience across Webflow and Wix Studio projects. I focus on clean, fast, conversion-ready builds tailored to each client's business.",
    email: 'harishkhuva958@gmail.com',
    phone: '+91 8866390382',
    location: 'India · Available Worldwide',
    years_exp: '3+',
    projects_count: '50+',
    available: true,
  },
  skills: [
    { text: 'WordPress Development (Elementor, Divi, Custom Themes) — 40+ sites', sort_order: 0 },
    { text: 'Shopify Store Setup & Customization — 10+ stores', sort_order: 1 },
    { text: 'GoHighLevel (GHL) API Integrations', sort_order: 2 },
    { text: 'Webflow Development', sort_order: 3 },
    { text: 'Wix Studio', sort_order: 4 },
    { text: 'Responsive & Performance Optimization', sort_order: 5 },
  ],
  platforms: [
    { name: 'WordPress', count: '40+', glyph: 'W', color_class: 'text-brand-700', bg_class: 'bg-brand-50', sort_order: 0 },
    { name: 'Shopify', count: '10+', glyph: 'S', color_class: 'text-emerald-700', bg_class: 'bg-emerald-50', sort_order: 1 },
    { name: 'Webflow', count: '5+', glyph: 'F', color_class: 'text-blue-700', bg_class: 'bg-blue-50', sort_order: 2 },
    { name: 'GHL', count: '8+', glyph: 'G', color_class: 'text-violet-700', bg_class: 'bg-violet-50', sort_order: 3 },
    { name: 'Wix Studio', count: '5+', glyph: 'X', color_class: 'text-amber-700', bg_class: 'bg-amber-50', sort_order: 4 },
  ],
  projects: [
    { title: 'Bella Cosmetics — E-Commerce Store', platform: 'Shopify', category: 'E-Commerce', description: 'Full Shopify store build with custom theme, upsell funnels, and conversion-optimized product pages.', tags: 'Liquid, Custom Theme, Klaviyo', accent: 'from-emerald-400 to-teal-500', image_url: '', sort_order: 0 },
    { title: 'Northstar Realty — Property Listings', platform: 'WordPress', category: 'Real Estate', description: 'Custom WordPress theme with advanced IDX integration, property search filters, and lead capture forms.', tags: 'Elementor, IDX, Custom Theme', accent: 'from-brand-400 to-brand-600', image_url: '', sort_order: 1 },
    { title: 'FitCore Gym — Membership Funnel', platform: 'GHL', category: 'Marketing', description: 'GoHighLevel funnel with calendar booking, SMS automation, and API integration for membership management.', tags: 'GHL API, Automation, Funnels', accent: 'from-violet-400 to-purple-500', image_url: '', sort_order: 2 },
    { title: 'Lumen Architecture — Portfolio Site', platform: 'Webflow', category: 'Portfolio', description: 'Award-style Webflow build with CMS-driven project gallery, smooth scroll animations, and SEO optimization.', tags: 'CMS, GSAP, SEO', accent: 'from-blue-400 to-indigo-500', image_url: '', sort_order: 3 },
    { title: 'Urban Eats — Restaurant Website', platform: 'WordPress', category: 'Restaurant', description: 'WordPress + Divi build with online ordering integration, reservation system, and responsive menu design.', tags: 'Divi, WooCommerce, Responsive', accent: 'from-brand-400 to-teal-600', image_url: '', sort_order: 4 },
    { title: 'Zenith Wellness — Booking Platform', platform: 'GHL', category: 'Health & Wellness', description: 'GHL sub-account setup with custom API workflows, automated email sequences, and pipeline management.', tags: 'GHL API, Workflows, Pipelines', accent: 'from-violet-400 to-fuchsia-500', image_url: '', sort_order: 5 },
    { title: 'Apex Gear — Sports Retail Store', platform: 'Shopify', category: 'E-Commerce', description: 'Shopify store with custom product configurator, subscription model, and multi-currency checkout.', tags: 'Liquid, Subscriptions, Multi-currency', accent: 'from-emerald-400 to-green-600', image_url: '', sort_order: 6 },
    { title: 'Maison Interiors — Design Studio', platform: 'Wix Studio', category: 'Interior Design', description: 'Wix Studio build with interactive portfolio grid, Velo-powered contact forms, and parallax scrolling.', tags: 'Velo, Parallax, Custom', accent: 'from-amber-400 to-orange-500', image_url: '', sort_order: 7 },
    { title: 'TechFlow SaaS — Landing Page', platform: 'WordPress', category: 'SaaS', description: 'High-converting WordPress landing page with A/B tested CTA sections, lead magnets, and analytics tracking.', tags: 'Custom Theme, A/B Testing, Analytics', accent: 'from-brand-400 to-cyan-600', image_url: '', sort_order: 8 },
    { title: 'GreenLeaf Organics — DTC Store', platform: 'Shopify', category: 'E-Commerce', description: 'Shopify DTC store with subscription bundles, review integrations, and speed-optimized product pages.', tags: 'Liquid, ReCharge, Reviews', accent: 'from-emerald-400 to-teal-600', image_url: '', sort_order: 9 },
    { title: 'Vertex Consulting — Corporate Site', platform: 'Webflow', category: 'Corporate', description: 'Webflow corporate site with team CMS, case study layouts, and advanced interactions for scroll-driven storytelling.', tags: 'CMS, Interactions, Corporate', accent: 'from-blue-400 to-sky-600', image_url: '', sort_order: 10 },
    { title: 'Pulse Fitness — Lead Gen Funnel', platform: 'GHL', category: 'Marketing', description: 'GHL funnel with multi-step survey, trigger links, and automated follow-up sequences via SMS and email.', tags: 'GHL API, Surveys, SMS Automation', accent: 'from-violet-400 to-purple-600', image_url: '', sort_order: 11 },
  ],
  services: [
    { title: 'WordPress Development', description: 'Custom themes, Elementor/Divi builds, WooCommerce stores, and performance-tuned WordPress sites built to convert.', price: 'From $499', features: 'Custom Theme Development, Elementor & Divi Expert, WooCommerce Setup, Speed & SEO Optimization', icon: 'globe', sort_order: 0 },
    { title: 'Shopify Store Setup', description: 'Complete Shopify store builds with custom Liquid sections, app integrations, and conversion-focused design.', price: 'From $799', features: 'Custom Theme & Liquid, Product Page Optimization, Payment & App Setup, Conversion Funnels', icon: 'shopping-bag', sort_order: 1 },
    { title: 'GHL API Integration', description: 'Custom GoHighLevel API workflows, automation pipelines, funnel builds, and sub-account management.', price: 'From $599', features: 'Custom API Workflows, Funnel & Pipeline Setup, SMS & Email Automation, Calendar & Booking Integration', icon: 'workflow', sort_order: 2 },
    { title: 'Webflow / Wix Development', description: 'Pixel-perfect Webflow and Wix Studio builds with CMS, interactions, and responsive design from the ground up.', price: 'From $699', features: 'Webflow CMS & Interactions, Wix Studio & Velo, Responsive Design, SEO & Performance', icon: 'layout', sort_order: 3 },
  ],
};
